### ISSUE TITLE
Opera 19, invalid detected

### ISSUE THREAD

**Issue by ntvsx193** [darcyclarke/Detect.js#21]
source: "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36 OPR/19.0.1326.63"

Result:
browser: Object
family: "Chrome"
major: 32
minor: 0
name: "Chrome 32"
patch: 1700
version: "32"

**Comment by AdrianoCahete** [comment]
Works in latest version:

```
detect.parse(navigator.userAgent)
e.UserAgent {source: "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/5…hrome/45.0.2454.93 Safari/537.36 OPR/32.0.1948.69", browser: Object, os: Object, device: Object}
browser: Object
family: "Opera"
major: 32
minor: 0
name: "Opera 32"
patch: 1948
version: "32"
```
