### ISSUE TITLE
IE 11 doesn't detected

### ISSUE THREAD

**Issue by Umiks** [darcyclarke/Detect.js#24]
User agent Mozilla/5.0 (Windows NT 6.1; Trident/7.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko detected how Other
![ie11](https://cloud.githubusercontent.com/assets/8122492/3536050/d609269c-080b-11e4-8d55-6886c1815d9b.png)
Pls fix this.

**Comment by AdrianoCahete** [comment]
Works with latest build.
