### ISSUE TITLE
Windows 10 Detection

### ISSUE THREAD

**Issue by tankerkiller125** [darcyclarke/Detect.js#30]
Pull Request #29
Although windows 10 is still in development I feel that it would be a good idea to detect it.

**Comment by gaborbernat** [comment]
can we merge this?

**Comment by tankerkiller125** [comment]
You should be able too.. Just be warned that its untested.

**Comment by gaborbernat** [comment]
only @darcyclarke  can do this, I'm not a contributor :sob:  would gladly test it, and add it if I could
