### ISSUE TITLE
Add Edge Detection

### ISSUE THREAD

**Issue by AdrianoCahete** [darcyclarke/Detect.js#32]
As Windows 10 is being launched today, it's time to update with Edge and Win10 detections. Win10 already made in #30 (not tested), we just need a Edge detection.

[MSDN Windows10 UserAgents](https://msdn.microsoft.com/en-us/library/hh869301%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)

**Comment by gaborbernat** [comment]
cam  we  add this?

**Comment by julmot** [comment]
https://github.com/darcyclarke/Detect.js/issues/39

**Comment by julmot** [comment]
Closing it because it got merged.
