### ISSUE TITLE
MS Edge is detected as Chrome

### ISSUE THREAD

**Issue by julmot** [darcyclarke/Detect.js#39]
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by AdrianoCahete** [comment]
Fixed in PR #38 

But only @darcyclarke can merge,

**Comment by julmot** [comment]
This is crap.. Look at his "Public contributions" (stats). We should fork the project somewhere else and contribute it with more authorized and __active__ persons

**Comment by AdrianoCahete** [comment]
I don't know if he abandoned this project, but the lastest activity in this project is from May, 4 (with a file merge not-generated by npm). But if he really abandoned it, i can make my fork updated, 'cause we use it in my work.

**Comment by julmot** [comment]
I just created a new repo and added you as the administrator:
https://github.com/detectjs/detectjs
Please upload it there so we can all contribute together

**Comment by julmot** [comment]
@darcyclarke Closed without any comment? Will you contribute and merge pull requests in this repo actively?

**Comment by AdrianoCahete** [comment]
He put you and me as Collaborator, so we can push new modifications and merge PR's, as some others permissions too.

**Comment by darcyclarke** [comment]
@julmot @AdrianoCahete I'm looking at this right now. Lots to be done.

**Comment by julmot** [comment]
@darcyclarke Thank you for this information. What would you think about moving the project to a separate organization to keep developing flexible?

**Comment by darcyclarke** [comment]
@julmot I'm not sure about a separate org. I can't see the need for other repos that would be relevant to this project; That's usually my predicate for creating a new organization. I think it's definitely important to make sure development doesn't fall off a cliff again but I think that comes down to having good collaborators on board (which I'm hoping you and @AdrianoCahete can be). If not, then there's a lot of pressure on a admin/creator whether or not there's an organization.

**Comment by julmot** [comment]
@darcyclarke My philosophy is to have at least two repositories.
1. One that will host all regexes. A simple frontend application (e.g. with AngularJS) will show the supported browsers/os based on the database in this repository. This would close https://github.com/darcyclarke/Detect.js/issues/34
2. The second will host the detect.js-library for clientside browser/os-detection based on the database repository (will be loaded with e.g. bower)
This could be done with a separate organization.
