### ISSUE TITLE
JavaScript error on IE11

### ISSUE THREAD

**Issue by natskvi** [darcyclarke/Detect.js#44]
See attached screenshot.  Works correctly in Chrome and Firefox but generates a JavaScript error on Windows 7 Enterprise SP1 running IE11 update 11.0.28.
![detectjs error 1](https://cloud.githubusercontent.com/assets/11557692/13846878/8b4d74aa-ec20-11e5-902d-401e97be3e18.png)

**Comment by julmot** [comment]
Do you have enabled "Enterprise mode" or any compatibility mode?

**Comment by natskvi** [comment]
"Enterprise Mode" and any compatibility mode are not enabled.

**Comment by julmot** [comment]
Did you tried using [Bowser](https://github.com/ded/bowser)?

**Comment by natskvi** [comment]
I did not, although it was on my To-Try list.  Do you recommend that I try it?

**Comment by julmot** [comment]
I've never had a problem that made a switch necessary. However, it seems to have tests implemented, so maybe you have more luck with it. 
If you are trying it, I would love to hear your experience.

**Comment by natskvi** [comment]
Roger that.  Thank you for the quick response.

**Comment by AdrianoCahete** [comment]
Tested with IE11 @ Win10 and works flawless.

Do you have any sample who we can see/test?

**Comment by natskvi** [comment]
Our setup is IE11 @ Win7.  I don't have a ready sample, but paring down all the Ember and JavaScript libraries we pull in to isolate detectjs for test purposes is definitely the next logical step.

**Comment by AdrianoCahete** [comment]
Hmmm... I'll try to run a VM to test with IE11 @ Win7.

**Comment by natskvi** [comment]
We ended up switching to Bowser, and that fixed the problem we had with IE11.  Thanks for suggesting to switch to that library.
