### ISSUE TITLE
Would you please consider adding git tag for each version?

### ISSUE THREAD

**Issue by PeterDaveHello** [darcyclarke/Detect.js#46]
Hi there,

I'm Peter from CDNJS, the free and open source and community-driven public front-end web library CDN service, there is a request to add Detect.js on CDNJS, however, we can not easily decide the versions on the repo, it'll be good to add tag for the versions, and also our auto-updater can automatically add the new versions of Detect.js in the future, so hope you can consider that, thank you!

cc https://github.com/cdnjs/cdnjs/issues/7157

**Comment by AdrianoCahete** [comment]
It's a nice enhancement. I don't know if me, julian or darcyclarke will be time to do this soon, but i'll keep this issue open as enhancement tag.
I already putting my projects on time, i think soon i'll have time to do this.

**Comment by PeterDaveHello** [comment]
Looks nice!
