### ISSUE TITLE
Microsoft Egde detected as Chrome

### ISSUE THREAD

**Issue by felixheidecke** [darcyclarke/Detect.js#51]
I tested the lib on browserstack.com using the **IE13** setting (wich apparently is the EDGE browser).
The test result shows Chrome as the Browser wich is not correct in this case:

![win10_edge_13 0](https://cloud.githubusercontent.com/assets/12717530/22697785/d6bf871e-ed52-11e6-8395-9c3d14254224.png)

**Comment by AdrianoCahete** [comment]
Hi, tested here in actual Edge browser @ Win 10 (Anniversary Update) and works like as expected:

![edge_win10](https://cloud.githubusercontent.com/assets/37474/22848004/fd489ea0-efcf-11e6-8c5f-fc4deb230dbd.PNG)

Are you using the latest lib version? We fixed that problema a long time ago.

**Comment by felixheidecke** [comment]
Except vor the Versions, the user_agent string seems to be the same. I wonder, how I ended up with Chrome instead of Edge :confused:

**Comment by AdrianoCahete** [comment]
In fact, we had a version who ended in this problem, but it's has been fixed a long time ago.

Can you test again to I close this issue?
